# C1: Wprowadzenie do PyTorch

In [3]:
import torch
print('Używam torch', torch.__version__)

Używam torch 2.5.1


### 1. Wprowadzenie do PyTorch

Jak w każdym frameworku uczenia maszynowego, PyTorch udostępnia funkcje stochastyczne, takie jak generowanie liczb losowych. Jednak bardzo dobrą praktyką jest skonfigurowanie kodu tak, aby był odtwarzalny i korzystał dokładnie z tych samych liczb losowych. Dlatego poniżej ustawiamy ziarno (seed).

In [8]:
torch.manual_seed(123)

### 2. Tworzenie tensorów w PyTorch

In [57]:
#inicjalizacja tensora
x = torch.Tensor(2, 3, 4)
print(x)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


Funkcja `torch.Tensor` przydziela pamięć dla żądanego tensora, ale ponownie wykorzystuje wartości, które wcześniej znajdowały się w tej pamięci. Aby bezpośrednio przypisać wartości do tensora podczas jego inicjalizacji, istnieje wiele alternatyw, między innymi:

* `torch.zeros`: tworzy tensor wypełniony zerami
* `torch.ones`: tworzy tensor wypełniony jedynkami
* `torch.rand`: tworzy tensor z losowymi wartościami równomiernie rozłożonymi w przedziale od 0 do 1
* `torch.randn`: tworzy tensor z losowymi wartościami pochodzącymi z rozkładu normalnego o średniej 0 i wariancji 1
* `torch.arange`: tworzy tensor zawierający kolejne wartości z danego zakresu
* `torch.Tensor (lista wejściowa)`: tworzy tensor z elementów podanej listy


In [60]:
#pusty tensor 1D (skalar)
x = torch.empty(1)
print(x)

tensor([0.])


In [62]:
#pusty tensor 2D (macierz)
x = torch.empty(2,2)
print(x)

tensor([[-1.2772e-21,  8.2957e-43],
        [ 0.0000e+00,  0.0000e+00]])


In [64]:
#tensory wielowymiarowe
x = torch.empty(2,2,2)
print(x)

tensor([[[-1.2839e-21,  8.2957e-43],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]]])


In [66]:
#tensor liczb losowych w przedziale (0, 1)
x = torch.rand(3,3)
print(x)

tensor([[0.1459, 0.0969, 0.7076],
        [0.5112, 0.7050, 0.0114],
        [0.4702, 0.8526, 0.7320]])


In [70]:
#tensor liczb losowych: rozkład normalny
x = torch.randn(3,3)
print(x)

tensor([[-0.5500,  1.1138, -1.2306],
        [ 1.4138, -0.2184,  2.4353],
        [-0.2603, -0.7742, -0.8148]])


In [72]:
#tensor zer/jedynek
x = torch.zeros(2,2)
print(x)
x = torch.ones(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [74]:
# Utworzenie tensora z (zagnieżdżonej) listy
x = torch.Tensor([[1, 2], [3, 4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [79]:
# Utworzenie tensora z losowymi wartościami z przedziału 0–1 o kształcie [2, 3, 4]
x = torch.rand(2, 3, 4)
print(x)

tensor([[[0.5578, 0.6681, 0.9275, 0.3443],
         [0.6800, 0.9998, 0.2855, 0.9753],
         [0.2518, 0.7204, 0.6959, 0.6397]],

        [[0.8954, 0.2979, 0.6314, 0.5028],
         [0.1239, 0.3786, 0.1661, 0.7211],
         [0.5449, 0.5490, 0.3483, 0.5024]]])


#### Kształt (rozmiar) tensora można uzyskać w taki sam sposób jak w bibliotece NumPy (`x.shape`) albo używając metody `.size`:

In [90]:
shape = x.shape
print('shape: ', shape)

size = x.size()
print('size: ', size)

dim1, dim2, dim3 = x.size()
print('size: ', dim1, dim2, dim3)

shape:  torch.Size([2, 3, 4])
size:  torch.Size([2, 3, 4])
size:  2 3 4


#### Sprawdzenie i zmiana typy

In [95]:
#sprawdzenie typu
print(x.dtype)

torch.float32


In [97]:
#zmiana typu
x=torch.ones(2,2, dtype=torch.int) #inne typy: double, float, float16 itp.
print(x.dtype)

torch.int32


### 3. Tensor --> numpy, numpy --> tensor

In [106]:
#numpy -> tensor
np_array = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_array)

print('Macież numpy: ', np_array)
print('Tensor: ', tensor)

Macież numpy:  [[1 2]
 [3 4]]
Tensor:  tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [110]:
#tensor -> numpy
tensor = torch.arange(4)
np_arr = tensor.numpy()

print("PyTorch tensor:", tensor)
print("Numpy array:", np_arr)

PyTorch tensor: tensor([0, 1, 2, 3])
Numpy array: [0 1 2 3]


Konwersja tensorów do formatu numpy wymaga, aby tensor znajdował się w pamięci CPU, a nie GPU (więcej o obsłudze GPU w dalszej części). Jeśli tensor znajduje się na GPU, należy wcześniej wywołać na nim metodę `.cpu()`. W efekcie otrzymujemy zapis:

`np_arr = tensor.cpu().numpy()`


### 4. Operacje na tensorach

In [146]:
x=torch.rand(2, 2)
y=torch.rand(2, 2)
print(x); print(y)

tensor([[0.5201, 0.8118],
        [0.0585, 0.1142]])
tensor([[0.3338, 0.2122],
        [0.7579, 0.8533]])


In [152]:
#dodawanie
z = x + y
print(z)

#lub
z = torch.add(x, y)
print(z)

tensor([[0.8538, 1.0240],
        [0.8164, 0.9675]])
tensor([[0.8538, 1.0240],
        [0.8164, 0.9675]])


#### Wywołanie `x1 + x2` tworzy nowy tensor zawierający sumę dwóch wejściowych tensorów. Możemy jednak używać także operacji **in-place**, które są wykonywane bezpośrednio na pamięci tensora. W takim przypadku zmieniamy wartości `x2` bez możliwości ponownego odwołania się do jego wartości sprzed operacji. Przykład pokazano poniżej:


In [155]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
print("X1 (before)", x1)
print("X2 (before)", x2)

x2.add_(x1)
print("X1 (after)", x1)
print("X2 (after)", x2)

X1 (before) tensor([[0.0149, 0.0757, 0.0131],
        [0.6886, 0.9024, 0.1123]])
X2 (before) tensor([[0.2685, 0.6591, 0.1735],
        [0.9247, 0.6166, 0.3608]])
X1 (after) tensor([[0.0149, 0.0757, 0.0131],
        [0.6886, 0.9024, 0.1123]])
X2 (after) tensor([[0.2834, 0.7348, 0.1866],
        [1.6134, 1.5190, 0.4731]])


In [157]:
#odejmowanie
z=x-y
print(z)

#lub
z = torch.sub(x,y)
print(z)

#lub
y.sub_(x)
print(y)

tensor([[ 0.1863,  0.5995],
        [-0.6994, -0.7391]])
tensor([[ 0.1863,  0.5995],
        [-0.6994, -0.7391]])
tensor([[-0.1863, -0.5995],
        [ 0.6994,  0.7391]])


#### Kolejną często wykonywaną operacją jest zmiana kształtu tensora. Tensor o rozmiarze `(2, 3)` można przekształcić w dowolny inny kształt zawierający taką samą liczbę elementów (np. tensor o rozmiarze `(6)` lub `(3, 2)` itd.). W PyTorch operacja ta nazywa się `view`:

In [166]:
x = torch.arange(6)
print(x)

tensor([0, 1, 2, 3, 4, 5])


In [168]:
x = x.view(2, 3)
print(x)

tensor([[0, 1, 2],
        [3, 4, 5]])


In [172]:
#odwrócenie tensora
x = x.permute(1, 0)
print(x)

tensor([[0, 3],
        [1, 4],
        [2, 5]])


Inne często używane operacje to **mnożenie macierzy**, które jest kluczowe w sieciach neuronowych. Bardzo często mamy wektor wejściowy, który jest przekształcany za pomocą uczonej macierzy wag. Istnieje kilka sposobów i funkcji do wykonywania mnożenia macierzy, z których niektóre wymieniamy poniżej:

* `torch.matmul`: Wykonuje iloczyn macierzy dla dwóch tensorów, przy czym zachowanie zależy od ich wymiarów. Jeśli oba wejścia są macierzami (2-wymiarowymi tensorami), wykonuje standardowy iloczyn macierzy. Dla tensorów o wyższych wymiarach funkcja wspiera **broadcasting**. Może być też zapisywane jako `a @ b`, podobnie jak w NumPy.
* `torch.mm`: Wykonuje iloczyn macierzy dla dwóch macierzy, ale **nie wspiera broadcastingu**.
* `torch.bmm`: Wykonuje iloczyn macierzy z obsługą wymiaru batch. Jeśli pierwszy tensor ma kształt `(b, n, m)`, a drugi `(b, m, p)`, wynikowy tensor będzie miał kształt `(b, n, p)` i jest obliczany jako `b` mnożeń macierzy dla każdej pary podmacierzy.
* `torch.einsum`: Wykonuje mnożenia macierzy i inne operacje (np. sumy iloczynów) używając **konwencji sumowania Einsteina**. 

Najczęściej używamy `torch.matmul` lub `torch.bmm`. Poniżej możemy spróbować mnożenia macierzy przy użyciu `torch.matmul`.

In [176]:
x = torch.arange(6)
x = x.view(2, 3)
print('X = ', x)

X =  tensor([[0, 1, 2],
        [3, 4, 5]])


In [180]:
y = torch.arange(9).view(3, 3)
print('Y = ', y)

Y =  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [184]:
z = torch.matmul(x, y)
print(z)
# sprawdź wynik ręcznie ;)

tensor([[15, 18, 21],
        [42, 54, 66]])


### 5. Indeksowanie

In [17]:
#przeglądanie wybranych elementów tensorów
x = torch.rand(4,5)
print(x)

print(x[:, 0]) #tylko 1-sza kolumna
print(x[:, 3]) #tylko 2-ga kolumna
print(x[1, :]) #drugi wiersz
print(x[1, 2]) #pojedyńczy element
print(x[1, 2].item()) #j. w.
print(x[0:2 :]) #dwa pierwsze wiersze itd.

tensor([[0.5291, 0.9851, 0.1887, 0.2871, 0.7830],
        [0.8124, 0.8473, 0.2611, 0.7809, 0.1405],
        [0.0445, 0.2247, 0.0915, 0.1061, 0.3949],
        [0.8410, 0.1360, 0.4670, 0.4914, 0.3414]])
tensor([0.5291, 0.8124, 0.0445, 0.8410])
tensor([0.2871, 0.7809, 0.1061, 0.4914])
tensor([0.8124, 0.8473, 0.2611, 0.7809, 0.1405])
tensor(0.2611)
0.261138916015625
tensor([[0.5291, 0.9851, 0.1887, 0.2871, 0.7830],
        [0.8124, 0.8473, 0.2611, 0.7809, 0.1405]])


### 6. Użycie GPU

In [188]:
if torch.cuda.is_available():
    dev = torch.device("cuda")
    x = torch.ones(4, device=dev) #implementacja na GPU
    
    #utworzenie tensora na CPU i przesunięcie na GPU
    y = torch.ones(4)
    t = t.to(dev)
    
    z = x+y    #operacja wykonywana z użyciem GPU
    z = z.to("cpu") #powrót na CPU
    print(z)