# Backpropagation

https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html




In [44]:
import torch

Pierwszą rzeczą, którą musimy zrobić, jest określenie, które tensory wymagają obliczania gradientów. Domyślnie, gdy tworzymy tensor, nie wymaga on obliczania gradientów.

In [17]:
x = torch.ones((3,))
print(x)
print(x.requires_grad)

tensor([1., 1., 1.])
False


Możemy to zmienić dla już istniejącego tensora, używając funkcji requires_grad_() (podkreślenie oznacza, że jest to operacja wykonywana w miejscu, czyli modyfikująca obiekt bez tworzenia kopii). Alternatywnie, podczas tworzenia tensora można przekazać argument requires_grad=True do większości wcześniej używanych funkcji inicjalizujących.

In [24]:
x.requires_grad_(True)
print(x.requires_grad)

True


In [26]:
#inicjalizacja tensora + obliczenie gradientu
a=torch.tensor([1.0],requires_grad=True)
x=torch.tensor([-2.],requires_grad=True)

In [30]:
#przykład
Q=a**2+x**3
print(Q)

tensor([-7.], grad_fn=<AddBackward0>)


In [32]:
#liczymy gradient 
Q.backward()

In [34]:
print("Dq/Da=",a.grad)
print("Dq/Dx=",x.grad)

Dq/Da= tensor([2.])
Dq/Dx= tensor([12.])


### This will fail

In [37]:
a=torch.tensor([1.0,2.0],requires_grad=True)
x=torch.tensor([-2.,-3.0],requires_grad=True)
Q=a**2+x**3
print(Q)
Q.backward()
print("Dq/Da=",a.grad)
print("Dq/Dx=",x.grad)

tensor([ -7., -23.], grad_fn=<AddBackward0>)


RuntimeError: grad can be implicitly created only for scalar outputs

## This will work

In [40]:
a=torch.tensor([1.0,2.0],requires_grad=True)
x=torch.tensor([-2.,-3.0],requires_grad=True)
Q=a**2+x**3
print(Q)
Q.backward(gradient=torch.tensor([1.0,1.0]))
print("Dq/Da=",a.grad)
print("Dq/Dx=",x.grad)

tensor([ -7., -23.], grad_fn=<AddBackward0>)
Dq/Da= tensor([2., 4.])
Dq/Dx= tensor([12., 27.])
